#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Tie-Simple
Version  : 1.04
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/H/HA/HANENKAMP/Tie-Simple-1.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/H/HA/HANENKAMP/Tie-Simple-1.04.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtie-simple-perl/libtie-simple-perl_1.04-1.debian.tar.xz
Summary  : 'Variable ties made much easier: much, much, much easier...'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Tie-Simple-license
Requires: perl-Tie-Simple-man

%description
This archive contains the distribution Tie-Simple,
version 1.04:
Variable ties made much easier: much, much, much easier...

%package license
Summary: license components for the perl-Tie-Simple package.
Group: Default

%description license
license components for the perl-Tie-Simple package.


%package man
Summary: man components for the perl-Tie-Simple package.
Group: Default

%description man
man components for the perl-Tie-Simple package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Tie-Simple-1.04
mkdir -p %{_topdir}/BUILD/Tie-Simple-1.04/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Tie-Simple-1.04/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Tie-Simple
cp LICENSE %{buildroot}/usr/share/doc/perl-Tie-Simple/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Tie/Simple.pm
/usr/lib/perl5/site_perl/5.26.1/Tie/Simple/Array.pm
/usr/lib/perl5/site_perl/5.26.1/Tie/Simple/Handle.pm
/usr/lib/perl5/site_perl/5.26.1/Tie/Simple/Hash.pm
/usr/lib/perl5/site_perl/5.26.1/Tie/Simple/Scalar.pm
/usr/lib/perl5/site_perl/5.26.1/Tie/Simple/Util.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Tie-Simple/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Tie::Simple.3
/usr/share/man/man3/Tie::Simple::Array.3
/usr/share/man/man3/Tie::Simple::Handle.3
/usr/share/man/man3/Tie::Simple::Hash.3
/usr/share/man/man3/Tie::Simple::Scalar.3
/usr/share/man/man3/Tie::Simple::Util.3
