#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Tie-Simple
Version  : 1.04
Release  : 26
URL      : https://cpan.metacpan.org/authors/id/H/HA/HANENKAMP/Tie-Simple-1.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/H/HA/HANENKAMP/Tie-Simple-1.04.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtie-simple-perl/libtie-simple-perl_1.04-1.debian.tar.xz
Summary  : 'Variable ties made much easier: much, much, much easier...'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Tie-Simple-license = %{version}-%{release}
Requires: perl-Tie-Simple-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution Tie-Simple,
version 1.04:
Variable ties made much easier: much, much, much easier...

%package dev
Summary: dev components for the perl-Tie-Simple package.
Group: Development
Provides: perl-Tie-Simple-devel = %{version}-%{release}
Requires: perl-Tie-Simple = %{version}-%{release}

%description dev
dev components for the perl-Tie-Simple package.


%package license
Summary: license components for the perl-Tie-Simple package.
Group: Default

%description license
license components for the perl-Tie-Simple package.


%package perl
Summary: perl components for the perl-Tie-Simple package.
Group: Default
Requires: perl-Tie-Simple = %{version}-%{release}

%description perl
perl components for the perl-Tie-Simple package.


%prep
%setup -q -n Tie-Simple-1.04
cd %{_builddir}
tar xf %{_sourcedir}/libtie-simple-perl_1.04-1.debian.tar.xz
cd %{_builddir}/Tie-Simple-1.04
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Tie-Simple-1.04/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Tie-Simple
cp %{_builddir}/Tie-Simple-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Tie-Simple/a8a0309a04c58e6cfc53cc5980833f4be93fe5ef || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Tie::Simple.3
/usr/share/man/man3/Tie::Simple::Array.3
/usr/share/man/man3/Tie::Simple::Handle.3
/usr/share/man/man3/Tie::Simple::Hash.3
/usr/share/man/man3/Tie::Simple::Scalar.3
/usr/share/man/man3/Tie::Simple::Util.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Tie-Simple/a8a0309a04c58e6cfc53cc5980833f4be93fe5ef

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
